# Generated by Django 5.2.5 on 2025-10-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='EstadosPedidos',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados Pedidos',
                'db_table': 'estados_pedidos',
            },
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id_forma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'formas_pago',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=40, null=True)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('precio_costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=120)),
                ('cuit', models.CharField(max_length=30, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='TiposProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Producto',
                'db_table': 'tipos_producto',
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_hora_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('total_ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_egresos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caja_cerrada', models.IntegerField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='core.empleados')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
            },
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='core.compras')),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
            ],
            options={
                'verbose_name_plural': 'Detalles Compra',
                'db_table': 'detalles_compra',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_forma', models.ForeignKey(blank=True, db_column='id_forma', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.formaspago')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.PROTECT, to='core.cajas')),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compras')),
                ('id_forma', models.ForeignKey(blank=True, db_column='id_forma', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.formaspago')),
                ('id_pago', models.ForeignKey(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pagos')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'movimientos_caja',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estadospedidos')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='pagos',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedidos'),
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_diseno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margen_ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_presupuesto', models.CharField(blank=True, max_length=30, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestosInsumos',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
                ('id_presupuesto', models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.CASCADE, to='core.presupuestos')),
            ],
            options={
                'verbose_name_plural': 'Presupuestos Insumos',
                'db_table': 'presupuestos_insumos',
            },
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='core.pedidos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='core.productos')),
            ],
            options={
                'verbose_name_plural': 'Pedidos Productos',
                'db_table': 'pedidos_productos',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='core.proveedores'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tiposproducto'),
        ),
    ]
