# Generated by Django 5.2.5 on 2025-10-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='contacto',
        ),
    ]
