# Generated by Django 5.2.5 on 2025-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_proveedores_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
