# Generated by Django 5.2.7 on 2025-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proveedores_email_proveedores_persona_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(default='Proveedor sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
