# Generated by Django 5.2.7 on 2025-10-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proveedores_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='ciudad',
        ),
    ]
