# Generated by Django 5.2.5 on 2025-10-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_dni_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='cargo',
            new_name='rol',
        ),
    ]
