# Generated by Django 5.2.5 on 2025-10-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cargo_empleados_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
