# Generated by Django 5.2.5 on 2025-10-28 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empleados_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rol',
            field=models.CharField(choices=[('Jefe', 'Jefe'), ('Empleado', 'Empleado'), ('Diseñador', 'Diseñador'), ('Producción', 'Producción')], default='Empleado', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
