# Generated by Django 5.2.5 on 2025-10-28 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empleados_user_alter_empleados_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajas',
            name='total_egresos',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='total_ingresos',
        ),
        migrations.AddField(
            model_name='cajas',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cajas',
            name='monto_fisico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cajas',
            name='saldo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='caja_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha_hora_apertura',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cajas',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleados'),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
