# Generated by Django 5.2.5 on 2025-10-28 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reset_movimientoscaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'formas_pago',
            },
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='id_forma',
        ),
        migrations.AlterModelOptions(
            name='cajas',
            options={},
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='id_caja',
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='id_compra',
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='id_movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='movimientoscaja',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='cajas',
            name='tolerancia',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='caja',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.cajas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='creado_por',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='core.empleados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COMPRA', 'Por compra'), ('VENTA', 'Por venta')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='referencia_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cajas',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha_hora_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.empleados'),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='monto_fisico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoscaja',
            name='descripcion',
            field=models.CharField(blank=True, default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoscaja',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientoscaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedidos'),
        ),
        migrations.CreateModel(
            name='AuditoriaCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(choices=[('ABRIR', 'Abrir caja'), ('CERRAR', 'Cerrar caja'), ('MOV_ALTA', 'Alta movimiento'), ('ERROR', 'Error de operación')], max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cajas')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimientoscaja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Caja',
                'verbose_name_plural': 'Auditoría de Caja',
                'db_table': 'auditoria_caja',
            },
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='forma_pago',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='core.formapago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_forma',
            field=models.ForeignKey(blank=True, db_column='id_forma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapago'),
        ),
        migrations.DeleteModel(
            name='FormasPago',
        ),
    ]
