# Generated by Django 5.2.5 on 2025-10-28 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sync_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha_hora_apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleados'),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='monto_fisico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='tolerancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
