# Generated by Django 5.2.5 on 2025-10-29 14:24

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def ignore_if_exists(apps, schema_editor):
    table = schema_editor.connection.introspection.table_names()
    if 'core_compras' in table:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE core_compras
                ADD COLUMN IF NOT EXISTS empleado_id INT NULL;
            """)  # para MySQL, si tu versión no soporta IF NOT EXISTS, no explode
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cajas_descripcion_alter_cajas_fecha_hora_apertura_and_more'),  
    ]

    operations = [

        migrations.RunPython(ignore_if_exists, reverse_code=migrations.RunPython.noop),

        migrations.AddField(
            model_name='compras',
            name='empleado',
            field=models.ForeignKey(
                to='core.empleados',
                on_delete=models.PROTECT,
                default=1,
            ),
        ),

        migrations.AddField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(default=timezone.now),
        ),

        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(
                to='core.proveedores',
                on_delete=models.PROTECT,
                default=1,
            ),
        ),

        migrations.AddField(
            model_name='compras',
            name='total',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
    ]
