# Generated by Django 5.2.5 on 2025-10-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_compras_costo_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='id_proveedor',
        ),
        migrations.AlterField(
            model_name='compras',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleados'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedores'),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compras')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.DeleteModel(
            name='DetallesCompra',
        ),
    ]
