# Generated by Django 5.2.7 on 2025-10-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_compras_costo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.proveedores'),
        ),
    ]
