# Generated by Django 5.2.5 on 2025-10-29 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_insumos_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='core.compras')),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='core.insumos')),
            ],
            options={
                'db_table': 'detalles_compra',
            },
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
