# Generated by Django 5.2.7 on 2025-10-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_detallescompra_delete_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_tipo',
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='insumo',
            field=models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, to='core.insumos'),
        ),
        migrations.DeleteModel(
            name='TiposProducto',
        ),
    ]
