# Generated by Django 5.2.7 on 2025-10-30 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_productos_id_tipo_alter_detallescompra_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='00000000', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='sin_email@dominio.com', max_length=100, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='000000000', max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PedidosInsumos',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.insumos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedidos')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'unique_together': {('pedido', 'insumo')},
            },
        ),
    ]
