# Generated by Django 5.2.7 on 2025-11-07 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20251107_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'tipos_producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='insumos',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='StockMovimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'stock_movimientos',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(db_column='id_tipo_producto', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tiposproducto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida'),
        ),
    ]
