# Generated by Django 5.2.7 on 2025-11-07 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tiposproducto_unidadmedida_insumos_factor_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestosinsumos',
            old_name='id_presupuesto',
            new_name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='presupuestosinsumos',
            name='id_insumo',
        ),
        migrations.AddField(
            model_name='presupuestosinsumos',
            name='insumo',
            field=models.ForeignKey(blank=True, db_column='id_insumo', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.insumos'),
        ),
        migrations.AddField(
            model_name='presupuestosinsumos',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.productos'),
        ),
        migrations.AlterField(
            model_name='presupuestosinsumos',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuestosinsumos',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductosInsumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'verbose_name': 'Producto-Insumo',
                'verbose_name_plural': 'Productos-Insumos',
                'db_table': 'productos_insumos',
            },
        ),
    ]
