# Generated by Django 5.2.7 on 2025-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_id_presupuesto_presupuestosinsumos_presupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(blank=True, db_column='unidad_medida', max_length=40, null=True),
        ),
    ]
