# Generated by Django 5.2.7 on 2025-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_insumos_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='unidad_medida',
        ),
    ]
