# Generated by Django 5.2.7 on 2025-11-07 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_unidadmedida_id_alter_unidadmedida_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovimientos',
            options={'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.RemoveField(
            model_name='stockmovimientos',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='stockmovimientos',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='stockmovimientos',
            name='id_movimiento',
        ),
        migrations.AddField(
            model_name='stockmovimientos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovimientos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmovimientos',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumos'),
        ),
        migrations.AlterField(
            model_name='stockmovimientos',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
