# Generated by Django 5.2.7 on 2025-11-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_stockmovimientos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
