# Generated by Django 5.2.7 on 2025-11-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_presupuestos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('otros_detalles', models.TextField(blank=True, null=True)),
                ('firma_autorizada', models.CharField(blank=True, max_length=255, null=True)),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='firmas/')),
            ],
            options={
                'db_table': 'configuracion_empresa',
            },
        ),
    ]
