# Generated by Django 5.2.7 on 2025-11-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_configuracionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_remitente', models.EmailField(blank=True, max_length=254, null=True)),
                ('contraseña_app', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('usar_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Configuración de Email',
                'db_table': 'configuracion_email',
            },
        ),
    ]
