# Generated by Django 5.2.7 on 2025-11-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_configuracionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
