# Generated by Django 5.2.7 on 2025-11-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_presupuestos_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestosProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trabajo', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.presupuestos')),
            ],
            options={
                'db_table': 'presupuestos_productos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='core.presupuestos')),
            ],
        ),
    ]
