# Generated by Django 5.2.7 on 2025-11-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_presupuestosproductos_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestosinsumos',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajo'),
        ),
    ]
