# Generated by Django 5.2.7 on 2025-11-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_presupuestosinsumos_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_presupuesto', to='core.presupuestos')),
            ],
            options={
                'db_table': 'trabajos_presupuesto',
            },
        ),
    ]
