# Generated by Django 5.2.7 on 2025-11-09 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_trabajopresupuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'verbose_name_plural': 'Trabajos'},
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='subtotal_trabajo',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='costo_diseno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subtotal_insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='nombre_trabajo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='presupuesto',
            field=models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='core.presupuestos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total_trabajo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='trabajo',
            table='trabajos',
        ),
        migrations.CreateModel(
            name='TrabajoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
                ('trabajo', models.ForeignKey(db_column='id_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.trabajo')),
            ],
            options={
                'verbose_name_plural': 'Trabajo Insumos',
                'db_table': 'trabajos_insumos',
            },
        ),
        migrations.DeleteModel(
            name='TrabajoPresupuesto',
        ),
    ]
