# Generated by Django 5.2.5 on 2025-11-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_trabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='estado_presupuesto',
            field=models.CharField(choices=[('EN ESPERA', 'En espera de aprobación'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='EN ESPERA', max_length=20),
        ),
    ]
