# Generated by Django 5.2.5 on 2025-11-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20251113_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
    ]
