# Generated by Django 5.2.5 on 2025-11-13 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_productos_options_remove_productos_id_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovimientos',
            options={'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id_tipo',
        ),
        migrations.RemoveField(
            model_name='stockmovimientos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='stockmovimientos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tiposproducto',
            name='id_tipo_producto',
        ),
        migrations.RemoveField(
            model_name='tiposproducto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='productos',
            name='costo_diseno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productos',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockmovimientos',
            name='detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockmovimientos',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovimientos',
            name='id_movimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tiposproducto',
            name='id_tipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tiposproducto',
            name='nombre_tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.tiposproducto'),
        ),
        migrations.AlterField(
            model_name='stockmovimientos',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumos'),
        ),
        migrations.AlterField(
            model_name='stockmovimientos',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
    ]
