# Generated by Django 5.2.5 on 2025-11-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_stockmovimientos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='costo_diseno',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.tiposproducto'),
        ),
    ]
