# Generated by Django 5.2.5 on 2025-11-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_presupuestos_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
