# Generated by Django 5.2.5 on 2025-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_pedidos_stock_descontado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
