# Generated by Django 5.2.7 on 2025-11-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_insumos_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
