# Generated by Django 5.2.7 on 2025-11-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_productos_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
