# Generated by Django 5.2.5 on 2025-11-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_productos_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='costo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleados'),
        ),
    ]
