# Generated by Django 5.2.5 on 2025-11-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_productos_costo_inicial_alter_cajas_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
