# Generated by Django 5.2.7 on 2025-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_insumos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoscaja',
            name='revertido',
            field=models.BooleanField(default=False),
        ),
    ]
